# Generated by Django 3.0.3 on 2020-02-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.PositiveIntegerField()),
                ('lng', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=48)),
            ],
        ),
    ]
