# Generated by Django 3.0.3 on 2020-02-08 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fahrenheit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fahrenheit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DHT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('heat_index', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.HeatIndex')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Station')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                  to='app.Temperature')),
            ],
        ),
    ]
