# Generated by Django 3.0.3 on 2020-02-08 20:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_temt6000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='heatindex',
            unique_together={('celsius', 'fahrenheit')},
        ),
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together={('celsius', 'fahrenheit')},
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pascal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilopascal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mbar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('pascal', 'kilopascal', 'mbar')},
            },
        ),
        migrations.CreateModel(
            name='BME280',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pressure')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                  to='app.Temperature')),
            ],
        ),
    ]
