# Generated by Django 3.0.3 on 2020-02-08 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200208_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kmph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
