# Generated by Django 3.0.3 on 2020-02-08 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Averages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                  to='app.Temperature')),
            ],
        ),
    ]
