# Generated by Django 3.0.3 on 2020-02-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_averages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='lng',
            field=models.FloatField(),
        ),
    ]
